Fix missing-prototypes
middlelayer.c:331:1: error: no previous prototype for 'cleanup_interfaces' [-Werror=missing-prototypes]
acpi.c:936:1: error: no previous prototype for 'get_acpi_info' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>